FROM node:20-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat
 
WORKDIR /app

COPY package*.json ./
COPY .npmrc ./

RUN npm install yarn

COPY . ./

RUN yarn install

FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN yarn build


FROM base AS runner

WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/ ./

USER nextjs

EXPOSE 3000
ENV PORT 3000

CMD yarn start

